stages:
  - test
  - build
  - deploy

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel

deploy:
  stage: deploy
  script:
    - echo "Uploading to GitLab package registry..."
  only:
    - main
