stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.11
  script:
    - pip install --upgrade pip setuptools wheel twine
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy:
  stage: deploy
  image: python:3.11
  script:
    - echo "🚀 Публікація пакета в GitLab Package Registry..."
    - pip install --upgrade twine
    - twine upload --repository-url https://gitlab.com/api/v4/projects/75437263/packages/pypi dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - main
